import type { GenerateDietPlanOutput } from '@/ai/flows/generate-diet-plan';
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from '@/components/ui/card';
import { ScrollArea } from '@/components/ui/scroll-area';
import { UtensilsCrossed } from 'lucide-react';

interface DietPlanDisplayProps {
  dietPlanOutput: GenerateDietPlanOutput;
}

export default function DietPlanDisplay({ dietPlanOutput }: DietPlanDisplayProps) {
  const { dietPlan } = dietPlanOutput;

  // Simple heuristic to split plan into sections if it uses "Day X:" or "Meal Y:"
  const sections = dietPlan.split(/\n(?=Day\s\d+:|Meal\s\d+:|Breakfast:|Lunch:|Dinner:|Snack:)/i);

  return (
    <Card className="mt-8 w-full max-w-3xl mx-auto shadow-xl">
      <CardHeader>
        <CardTitle className="flex items-center gap-2 text-2xl">
          <UtensilsCrossed className="text-primary" />
          Your Personalized Diet Plan
        </CardTitle>
        <CardDescription>
          Here is the diet plan generated by our AI based on your profile. Remember to consult with a healthcare professional before making significant dietary changes.
        </CardDescription>
      </CardHeader>
      <CardContent>
        <ScrollArea className="h-[400px] w-full p-4 border rounded-md bg-background">
          {sections.map((section, index) => {
            const lines = section.trim().split('\n');
            const title = lines[0];
            const content = lines.slice(1).join('\n');
            return (
              <div key={index} className="mb-4 last:mb-0">
                {title && <h3 className="font-semibold text-lg text-primary mb-1">{title}</h3>}
                <pre className="whitespace-pre-wrap text-sm leading-relaxed font-sans">
                  {content || (index === 0 && title)} 
                </pre>
              </div>
            );
          })}
        </ScrollArea>
      </CardContent>
    </Card>
  );
}
