
"use client";

import type { GenerateDietPlanOutput } from '@/ai/flows/generate-diet-plan-types';
import { Card, CardContent, CardDescription, CardHeader, CardTitle, CardFooter } from '@/components/ui/card';
import { ScrollArea } from '@/components/ui/scroll-area';
import { UtensilsCrossed, Info, Printer } from 'lucide-react';
import { Alert, AlertDescription, AlertTitle } from "@/components/ui/alert";
import { Button } from '@/components/ui/button';

interface DietPlanDisplayProps {
  dietPlanOutput: GenerateDietPlanOutput;
}

const renderDietPlanContent = (content: string): (JSX.Element | null)[] => {
  if (!content || content.trim() === '') return [];
  const lines = content.split('\n');
  const elements: (JSX.Element | null)[] = [];

  for (let i = 0; i < lines.length; i++) {
    const line = lines[i];
    const trimmedLine = line.trim();

    if (line.length === 0 && i > 0 && lines[i-1].length === 0) {
        // No specific element for a single empty line if paragraphs have margins.
    }

    if (trimmedLine === '') {
      continue;
    }

    if (trimmedLine.startsWith('**') && (trimmedLine.endsWith('**') || trimmedLine.endsWith('**:'))) {
      const headingText = trimmedLine.replace(/\*\*/g, '').replace(/:$/, '');
      elements.push(<h4 key={`h4-${i}-${headingText}`} className="text-md font-semibold mt-3 mb-1.5 text-primary">{headingText}</h4>);
      continue;
    }
    
    const listItemMatch = line.match(/^(\s*)(\*\s+)(.*)/);
    if (listItemMatch) {
      const indentSpaces = listItemMatch[1].length;
      let itemContent = listItemMatch[3]; 

      const indentLevel = Math.floor(indentSpaces / 2); 
      const marginLeft = `${indentLevel * 1.25}rem`; 

      if (itemContent.startsWith('*') && itemContent.endsWith('*') && itemContent.includes('Approximate Nutritional Information:')) {
        const nutritionalText = itemContent.substring(1, itemContent.length - 1);
        elements.push(<p key={`nutri-${i}-${nutritionalText.slice(0,10)}`} style={{ marginLeft }} className="text-xs italic text-muted-foreground my-0.5">{nutritionalText}</p>);
        continue;
      }
      
      const boldPartMatch = itemContent.match(/^\*\*(.*?)\*\*:\s*(.*)/s); 
      if (boldPartMatch) {
        const title = boldPartMatch[1];
        const description = boldPartMatch[2];
        elements.push(
          <div key={`li-bold-${i}-${title}`} style={{ marginLeft }} className="flex text-sm my-1">
             <span className="text-primary mr-2 mt-1 shrink-0">&#8226;</span>
            <div>
                <span className="font-semibold text-primary">{title}:</span>
                <span> {description}</span>
            </div>
          </div>
        );
        continue;
      }

      elements.push(
        <div key={`li-reg-${i}-${itemContent.slice(0,10)}`} style={{ marginLeft }} className="flex items-start text-sm my-1">
          <span className="text-primary mr-2 mt-1 shrink-0">&#8226;</span>
          <span className="flex-1">{itemContent}</span>
        </div>
      );
      continue;
    }
    
    elements.push(<p key={`p-${i}-${line.slice(0,10)}`} className="text-sm my-1.5 leading-relaxed">{line}</p>);
  }
  return elements.filter(Boolean); 
};


export default function DietPlanDisplay({ dietPlanOutput }: DietPlanDisplayProps) {
  const { dietPlan } = dietPlanOutput;

  const sections = dietPlan.split(/\n(?=Day\s\d+:|Meal\s\d+:|Breakfast:|Lunch:|Dinner:|Snack:|Important Notes and Adjustments:|Important Considerations:|Sample Meal Plan:)/i);

  const handlePrint = () => {
    window.print();
  };

  return (
    <Card id="dietPlanCardPrintable" className="mt-8 w-full max-w-3xl mx-auto shadow-xl">
      <CardHeader>
        <CardTitle className="flex items-center gap-2 text-2xl">
          <UtensilsCrossed className="text-primary" />
          Your Personalized Diet Plan
        </CardTitle>
        <CardDescription>
          Here is the diet plan generated by our AI based on your profile. Remember to consult with a healthcare professional before making significant dietary changes.
        </CardDescription>
      </CardHeader>
      <CardContent>
        <ScrollArea className="h-[500px] w-full p-4 border rounded-md bg-card print-expandable-scroll-area">
          {sections.map((sectionText, sectionIndex) => {
            const trimmedSectionText = sectionText.trim();
            if (!trimmedSectionText) return null;

            const sectionLines = trimmedSectionText.split('\n');
            let sectionTitle = '';
            let contentForRenderer = trimmedSectionText;

            const firstLine = sectionLines[0].trim();
            const majorTitleRegex = /^(Day\s\d+:|Meal\s\d+:|Breakfast:|Lunch:|Dinner:|Snack:|Important Notes and Adjustments:|Important Considerations:|Sample Meal Plan:)/i;
            
            if (majorTitleRegex.test(firstLine)) {
              sectionTitle = firstLine;
              if (sectionLines.length > 1) {
                contentForRenderer = sectionLines.slice(1).join('\n');
              } else {
                contentForRenderer = ''; 
              }
            }
            
            return (
              <div key={`${sectionIndex}-${sectionTitle.slice(0,5)}`} className="mb-5 last:mb-0">
                {sectionTitle && (
                  <h3 className="font-semibold text-lg md:text-xl text-primary mb-2.5 mt-4 first:mt-0">
                    {sectionTitle}
                  </h3>
                )}
                <div className="space-y-0.5"> 
                  {renderDietPlanContent(contentForRenderer)}
                </div>
              </div>
            );
          })}
        </ScrollArea>
        <Alert variant="default" className="mt-6 bg-primary/10 border-primary/30 text-primary">
          <Info className="h-4 w-4 text-primary" />
          <AlertTitle>Pro Tip!</AlertTitle>
          <AlertDescription className="text-primary/90">
            We recommend writing down your diet plan or making notes for easy reference. This can help you stay on track with your meals and goals!
          </AlertDescription>
        </Alert>
      </CardContent>
      <CardFooter className="justify-end pt-4">
        {/* Button removed as per user request */}
      </CardFooter>
    </Card>
  );
}
