
"use client";

import type { GenerateWorkoutScheduleOutput } from '@/ai/flows/generate-workout-schedule-types';
import { Card, CardContent, CardDescription, CardHeader, CardTitle, CardFooter } from '@/components/ui/card';
import { Accordion, AccordionContent, AccordionItem, AccordionTrigger } from '@/components/ui/accordion';
import { ScrollArea } from '@/components/ui/scroll-area';
import { Alert, AlertDescription, AlertTitle } from "@/components/ui/alert";
import { Button } from '@/components/ui/button';
import { ClipboardList, Zap, Info, Copy, Check } from 'lucide-react';
import { useState, useEffect } from 'react';
import { useToast } from '@/hooks/use-toast';


interface WorkoutScheduleDisplayProps {
  scheduleOutput: GenerateWorkoutScheduleOutput;
}

export default function WorkoutScheduleDisplay({ scheduleOutput }: WorkoutScheduleDisplayProps) {
  const { scheduleTitle, weeklySchedule, recoveryTips, disclaimer } = scheduleOutput;
  const { toast } = useToast();
  const [isCopied, setIsCopied] = useState(false);

  const formatScheduleForCopy = (): string => {
    let text = `${scheduleTitle || "Workout Schedule"}\n\n`;

    weeklySchedule.forEach(day => {
      text += `${day.dayName}: ${day.focus}\n`;
      day.exercises.forEach(exercise => {
        text += `  - ${exercise.name}${exercise.setsAndReps ? ` (${exercise.setsAndReps})` : ''}\n`;
      });
      text += "\n";
    });

    if (recoveryTips) {
      text += "Recovery & General Tips:\n";
      text += `${recoveryTips}\n\n`;
    }

    if (disclaimer) {
      text += "Disclaimer:\n";
      text += `${disclaimer}\n`;
    }
    return text;
  };

  const handleCopyToClipboard = async () => {
    const planText = formatScheduleForCopy();
    try {
      await navigator.clipboard.writeText(planText);
      toast({
        title: "Copied to Clipboard!",
        description: "The workout schedule has been copied.",
        variant: "default",
      });
      setIsCopied(true);
    } catch (err) {
      console.error('Failed to copy text: ', err);
      toast({
        title: "Copy Failed",
        description: "Could not copy the workout schedule to your clipboard.",
        variant: "destructive",
      });
      setIsCopied(false);
    }
  };

  useEffect(() => {
    if (isCopied) {
      const timer = setTimeout(() => {
        setIsCopied(false);
      }, 2500); // Reset after 2.5 seconds
      return () => clearTimeout(timer);
    }
  }, [isCopied]);


  return (
    <Card id="workoutScheduleCardPrintable" className="mt-8 w-full max-w-3xl mx-auto shadow-xl">
      <CardHeader>
        <CardTitle className="flex items-center gap-2 text-2xl">
          <ClipboardList className="text-primary" />
          {scheduleTitle || "Your Personalized Workout Schedule"}
        </CardTitle>
        <CardDescription>
          Here is the workout schedule generated by our AI. Remember to warm up before each session and cool down afterwards.
        </CardDescription>
      </CardHeader>
      <CardContent>
        <ScrollArea className="h-[500px] w-full p-1 border rounded-md bg-card print-expandable-scroll-area">
          <Accordion type="multiple" className="w-full px-3" defaultValue={weeklySchedule.map(day => day.dayName)}>
            {weeklySchedule.map((day, index) => (
              <AccordionItem value={day.dayName || `day-${index}`} key={day.dayName || `day-${index}`}>
                <AccordionTrigger className="text-lg font-semibold text-secondary-foreground hover:no-underline">
                  {day.dayName}: <span className="text-base font-medium text-primary ml-2">{day.focus}</span>
                </AccordionTrigger>
                <AccordionContent className="pl-2">
                  <ul className="space-y-2 mt-1">
                    {day.exercises.map((exercise, exIndex) => (
                      <li key={exIndex} className="text-sm p-2 bg-muted/50 rounded-md shadow-sm">
                        <strong className="text-foreground">{exercise.name}</strong>
                        {exercise.setsAndReps && (
                          <span className="block text-xs text-muted-foreground italic mt-0.5">
                            {exercise.setsAndReps}
                          </span>
                        )}
                      </li>
                    ))}
                  </ul>
                </AccordionContent>
              </AccordionItem>
            ))}
          </Accordion>

          {recoveryTips && (
            <div className="mt-6 p-3 border-t">
              <h3 className="flex items-center gap-2 text-lg font-semibold text-primary mb-2">
                <Zap className="w-5 h-5" />
                Recovery & General Tips
              </h3>
              <p className="text-sm whitespace-pre-line leading-relaxed text-muted-foreground">{recoveryTips}</p>
            </div>
          )}
          
        </ScrollArea>
        
        <Alert variant="default" className="mt-6 bg-primary/10 border-primary/30 text-primary">
          <Info className="h-4 w-4 text-primary" />
          <AlertTitle>Pro Tip!</AlertTitle>
          <AlertDescription>
            We recommend writing down your schedule or making notes for easy reference at the gym. This can help you stay on track!
          </AlertDescription>
        </Alert>
         
      </CardContent>
      <CardFooter className="justify-end pt-4">
        <Button onClick={handleCopyToClipboard} variant="outline" className="print-hide-button">
          {isCopied ? <Check className="mr-2 h-4 w-4 text-green-500" /> : <Copy className="mr-2 h-4 w-4" />}
          {isCopied ? 'Copied!' : 'Copy Plan'}
        </Button>
      </CardFooter>
    </Card>
  );
}

