
"use client";

import type { GenerateWorkoutScheduleOutput } from '@/ai/flows/generate-workout-schedule-types';
import { Card, CardContent, CardDescription, CardHeader, CardTitle, CardFooter } from '@/components/ui/card';
import { Accordion, AccordionContent, AccordionItem, AccordionTrigger } from '@/components/ui/accordion';
import { ScrollArea } from '@/components/ui/scroll-area';
import { ClipboardList, Zap, Info } from 'lucide-react';
// Removed FileDown, Loader2, Button, useState, useToast as they were for the PDF button
import { Alert, AlertDescription, AlertTitle } from "@/components/ui/alert";


interface WorkoutScheduleDisplayProps {
  scheduleOutput: GenerateWorkoutScheduleOutput;
}

export default function WorkoutScheduleDisplay({ scheduleOutput }: WorkoutScheduleDisplayProps) {
  const { scheduleTitle, weeklySchedule, recoveryTips, disclaimer } = scheduleOutput;
  // Removed isGeneratingPdf state and useToast hook

  // Removed handleSaveAsPdf function

  return (
    <Card id="workoutScheduleCardPrintable" className="mt-8 w-full max-w-3xl mx-auto shadow-xl">
      <CardHeader>
        <CardTitle className="flex items-center gap-2 text-2xl">
          <ClipboardList className="text-primary" />
          {scheduleTitle || "Your Personalized Workout Schedule"}
        </CardTitle>
        <CardDescription>
          Here is the workout schedule generated by our AI. Remember to warm up before each session and cool down afterwards.
        </CardDescription>
      </CardHeader>
      <CardContent>
        <ScrollArea className="h-[500px] w-full p-1 border rounded-md bg-card print-expandable-scroll-area">
          <Accordion type="multiple" className="w-full px-3" defaultValue={weeklySchedule.map(day => day.dayName)}>
            {weeklySchedule.map((day, index) => (
              <AccordionItem value={day.dayName || `day-${index}`} key={day.dayName || `day-${index}`}>
                <AccordionTrigger className="text-lg font-semibold text-secondary-foreground hover:no-underline">
                  {day.dayName}: <span className="text-base font-medium text-primary ml-2">{day.focus}</span>
                </AccordionTrigger>
                <AccordionContent className="pl-2">
                  <ul className="space-y-2 mt-1">
                    {day.exercises.map((exercise, exIndex) => (
                      <li key={exIndex} className="text-sm p-2 bg-muted/50 rounded-md shadow-sm">
                        <strong className="text-foreground">{exercise.name}</strong>
                        {exercise.setsAndReps && (
                          <span className="block text-xs text-muted-foreground italic mt-0.5">
                            {exercise.setsAndReps}
                          </span>
                        )}
                      </li>
                    ))}
                  </ul>
                </AccordionContent>
              </AccordionItem>
            ))}
          </Accordion>

          {recoveryTips && (
            <div className="mt-6 p-3 border-t">
              <h3 className="flex items-center gap-2 text-lg font-semibold text-primary mb-2">
                <Zap className="w-5 h-5" />
                Recovery & General Tips
              </h3>
              <p className="text-sm whitespace-pre-line leading-relaxed text-muted-foreground">{recoveryTips}</p>
            </div>
          )}
          
        </ScrollArea>
         {disclaimer && (
            <Alert variant="default" className="mt-6 bg-amber-50 border-amber-300 text-amber-800 print-expandable-scroll-area">
              <Info className="h-5 w-5 text-amber-600" />
              <AlertTitle className="font-semibold text-amber-700">Important Disclaimer</AlertTitle>
              <AlertDescription className="text-xs">
                {disclaimer}
              </AlertDescription>
            </Alert>
          )}
      </CardContent>
      <CardFooter className="justify-end">
         {/* Removed the "Save as PDF" Button */}
      </CardFooter>
    </Card>
  );
}
