
"use client";

import type { GenerateWorkoutScheduleOutput } from '@/ai/flows/generate-workout-schedule-types';
import { Card, CardContent, CardDescription, CardHeader, CardTitle, CardFooter } from '@/components/ui/card';
import { Accordion, AccordionContent, AccordionItem, AccordionTrigger } from '@/components/ui/accordion';
import { Alert, AlertDescription, AlertTitle } from "@/components/ui/alert";
import { Button } from '@/components/ui/button';
import { ClipboardList, Dumbbell, Info, Copy, Check } from 'lucide-react';
import { useState, useEffect } from 'react';
import { useToast } from '@/hooks/use-toast';

interface WorkoutScheduleDisplayProps {
  scheduleOutput: GenerateWorkoutScheduleOutput;
}

export default function WorkoutScheduleDisplay({ scheduleOutput }: WorkoutScheduleDisplayProps) {
  const { scheduleTitle, weeklySchedule, notes, disclaimer } = scheduleOutput;
  const { toast } = useToast();
  const [isCopied, setIsCopied] = useState(false);

  // Find the first workout day to open by default in the accordion
  const firstWorkoutDay = weeklySchedule.find(day => day.exercises.length > 0)?.day;

  const formatScheduleForCopy = (): string => {
    let text = `${scheduleTitle || "Your Weekly Workout Schedule"}\n\n`;

    weeklySchedule.forEach(day => {
      text += `--- ${day.day}: ${day.focus} ---\n`;
      if (day.exercises.length > 0) {
        day.exercises.forEach(exercise => {
          text += `  - ${exercise.name}: ${exercise.sets} sets of ${exercise.reps} reps\n`;
        });
      } else {
        text += "  Rest Day\n";
      }
      text += "\n";
    });

    if (notes) {
      text += "Important Notes:\n";
      text += `${notes}\n\n`;
    }

    if (disclaimer) {
      text += "Disclaimer:\n";
      text += `${disclaimer}\n`;
    }
    return text;
  };

  const handleCopyToClipboard = async () => {
    const planText = formatScheduleForCopy();
    try {
      await navigator.clipboard.writeText(planText);
      toast({
        title: "Copied to Clipboard!",
        description: "The workout schedule has been copied.",
        variant: "default",
      });
      setIsCopied(true);
    } catch (err) {
      console.error('Failed to copy text: ', err);
      toast({
        title: "Copy Failed",
        description: "Could not copy the schedule to your clipboard.",
        variant: "destructive",
      });
      setIsCopied(false);
    }
  };

   useEffect(() => {
    if (isCopied) {
      const timer = setTimeout(() => {
        setIsCopied(false);
      }, 2500);
      return () => clearTimeout(timer);
    }
  }, [isCopied]);


  return (
    <Card id="workoutScheduleCardPrintable" className="mt-8 w-full max-w-3xl mx-auto shadow-xl border-0 bg-transparent">
      <CardHeader className="text-center px-2">
        <div className="inline-flex items-center justify-center bg-primary/10 p-3 rounded-full mb-4 mx-auto w-fit">
            <ClipboardList className="w-8 h-8 text-primary" />
        </div>
        <CardTitle className="text-3xl font-bold">
          {scheduleTitle || "Your Weekly Workout Schedule"}
        </CardTitle>
        <CardDescription className="text-md max-w-lg mx-auto">
          Here is the weekly schedule generated by our AI. Remember to warm up before each session and cool down afterwards.
        </CardDescription>
      </CardHeader>
      <CardContent className="px-2">
          <Accordion type="single" collapsible defaultValue={firstWorkoutDay} className="w-full">
            {weeklySchedule.map((day) => (
              <AccordionItem value={day.day} key={day.day} className="border-b-0 mb-2">
                <AccordionTrigger className="py-3 px-4 rounded-lg bg-card text-foreground shadow-sm hover:no-underline data-[state=open]:bg-primary/10 data-[state=open]:shadow-md">
                  <div className="flex items-center justify-between w-full">
                    <h4 className="font-bold text-lg">{day.day}:</h4>
                    <span className="text-primary font-semibold text-lg">{day.focus}</span>
                  </div>
                </AccordionTrigger>
                <AccordionContent className="pt-2 pb-0">
                  {day.exercises.length > 0 ? (
                    <div className="space-y-2 pt-2">
                      {day.exercises.map((exercise, index) => (
                        <div key={index} className="bg-card p-4 rounded-lg shadow-sm">
                           <p className="font-bold text-md">{exercise.name}</p>
                           <p className="text-sm text-muted-foreground">{exercise.sets} sets of {exercise.reps} reps</p>
                        </div>
                      ))}
                    </div>
                  ) : (
                    <div className="p-4 text-center text-muted-foreground bg-card rounded-lg shadow-sm mt-2">
                      <p>Rest Day - a great time to recover and grow stronger!</p>
                    </div>
                  )}
                </AccordionContent>
              </AccordionItem>
            ))}
          </Accordion>

          {notes && (
            <div className="mt-6 p-4 rounded-lg bg-card shadow-sm">
              <h3 className="flex items-center gap-2 text-lg font-semibold text-primary mb-2">
                <Dumbbell className="w-5 h-5" />
                Important Notes
              </h3>
              <p className="text-sm whitespace-pre-line leading-relaxed text-muted-foreground">{notes}</p>
            </div>
          )}
      </CardContent>
       <CardFooter className="flex-col gap-4 pt-4 px-2">
         {disclaimer && (
            <Alert variant="default" className="w-full">
                <Info className="h-4 w-4" />
                <AlertTitle>Disclaimer</AlertTitle>
                <AlertDescription>
                {disclaimer}
                </AlertDescription>
            </Alert>
         )}
        <Button onClick={handleCopyToClipboard} variant="outline" className="w-full print-hide-button">
          {isCopied ? <Check className="mr-2 h-4 w-4 text-green-500" /> : <Copy className="mr-2 h-4 w-4" />}
          {isCopied ? 'Copied!' : 'Copy Schedule'}
        </Button>
      </CardFooter>
    </Card>
  );
}
